---
# Build goofys from source as the latest goofys release is from 2020 and is not compatible with IMDSv2
- name: Install goofys from source
  ansible.builtin.shell: |
    export GOPATH=$HOME/work
    go get github.com/kahing/goofys
    # Use the latest commit on the master branch at time of writing: 350ff3
    go install github.com/kahing/goofys@350ff312abaa1abcf21c5a06e143c7edffe9e2f4
  args:
    creates: /root/work/bin/goofys

- name: Copy goofys binary to a location that's on the path
  ansible.builtin.copy:
    src: /root/work/bin/goofys
    dest: /usr/local/bin/
    remote_src: true
    mode: 0755
    owner: root

- name: Create mount point
  ansible.builtin.file:
    path: "/{{ item.host_path }}"
    state: directory
  loop: "{{ mount_goofys_filesystems | default([]) }}"

- name: Create systemd service file to mount goofys
  ansible.builtin.template:
    src: 'roles/filesystem/templates/goofys-mount.service'
    dest: '/etc/systemd/system/goofys-mount-{{ item.name }}.service'
    mode: 0644
  vars:
    bucket_name: "{{ item.bucket_name }}"
    host_path: "{{ item.host_path }}"
    name: "{{ item.name }}"
  loop: "{{ mount_goofys_filesystems | default([]) }}"

- name: Start goofys service
  ansible.builtin.systemd:
    name: "goofys-mount-{{ item.name }}"
    enabled: true
    masked: false
    daemon_reload: true
    state: restarted
  loop: "{{ mount_goofys_filesystems | default([]) }}"
