---
- name: Run the common role across all hosts in the inventory
  hosts: all
  roles:
    - common

- name: Configure dnsmasq
  hosts: dc
  roles:
    - dnsmasq

- name: Configure nut ups
  hosts: nut
  roles:
    - nut
