---
- name: Ensure cron scripts directory exists
  ansible.builtin.file:
    path: "{{ cron_scripts_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

## Configure cron jobs.
# name, job, and a time interval are required.
# If a specific time is omitted, it will default to *
# If you need something simple like daily, or hourly, set the special time instead.
- name: Configure cron jobs
  ansible.builtin.cron:
    name: "{{ item.name }}"
    cron_file: "{{ item.name }}"
    job: "{{ item.job }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    special_time: "{{ item.special_time | default(omit) }}"
    user: "{{ item.user | default('root') }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ cron_jobs }}"
